name: Static Tests

on: 
  push:
  pull_request:

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2  
      - name: PHPStan
        run: bin/phpstan analyse src
      - name: PHPUnit
        run: bin/phpunit --testdox tests
