name: Static Tests

on: 
  push:
  pull_request:
    branches: [main]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: PHPStan
        uses: bin/phpstan analyse src
      - name: PHPUnit
        uses: bin/phpunit --testdox tests
